### ISSUE TITLE
Very good UI

### ISSUE THREAD

**Issue by Fastidious** [45678/miniLock-ID-inspector#1]
I really like your taste on UI design. Maybe you can re-work the one miniLock uses now? I find it slightly odd and busy at times, and prefer a darker theme rather than the two tones blue it currently has. The minilock-id-inspector has lovely colors/fonts.

**Comment by 45678** [comment]
Thanks for this comment @Fastidious. I am sorry it took me so long to follow-up. I wasn’t subscribed and I missed it originally.
