### ISSUE TITLE
Slight overflow

### ISSUE THREAD

**Issue by Fastidious** [45678/miniLock-ID-inspector#2]
See screenshot. :-)

![Bar overflow](https://cloud.githubusercontent.com/assets/8352292/3919411/25f97460-23a8-11e4-81cc-3d7b93c72acd.png)

**Comment by 45678** [comment]
Thanks for noticing this @Fastidious. Although it is aesthetically unusual I think I would prefer to leave it as is because the graphic is still accurate in this case.
